= Hostfully Java Technical Test
:author: Alexandre Paiva
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 2
:sectlinks:

= Overview

This repository contains a WebService that supports a REST API to handle bookings.

== Terminology

* A **booking** is when a **guest** selects a start and end date and submits a reservation on a property.
* A **block** is when the property owner or manager selects a range of days during which no guest can make a booking (e.g. the owner wants to use the property for themselves, or the **property** manager needs to schedule the repainting of a few rooms).

== Implementation

For allowing the management of hosting properties, `Hostfully` has the internal (*) API documented here.
This API allows the proper management of the before mentioned four entities: **Property**, **Guest**, **Booking**, and **Block**.

IMPORTANT: (*) The API was designed for internal usage only, mainly for Front-end integration or internal services.
Therefore, entity IDs are returned in the GET, POST, PUT, and PATCH responses.
If the API needs an extension to be external exposed, it should be refactored to return UUID instead.

include::architecture/architecture.adoc[]

include::api/api.adoc[]

