name: Release Workflow

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: GitHub Actions Release Demo
        uses: TheLogicalNights/GitHub-Actions-Release-Demo@v2.0.23

        with:
          api_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0
